#!/usr/bin/env python3
"""
Turn notes/codemap/functions.csv (from tools/ghidra/NameFromAsserts.java) into
the browsable code map: notes/codemap/README.md plus one page per source file.

    python3 tools/codemap.py            # rewrite notes/codemap/*.md
"""
import collections
import csv
import os

ROOT = os.path.join(os.path.dirname(__file__), "..", "notes", "codemap")


def main():
    rows = list(csv.DictReader(open(os.path.join(ROOT, "functions.csv"))))
    named, byfile, selfc = {}, collections.defaultdict(list), collections.defaultdict(set)
    for r in rows:
        if r["kind"] in ("callee", "callee-kept"):
            n = r["name"]
            if n.endswith(")") and n.split(" (")[0] == n.split(" (")[-1].rstrip(")"):
                n = n.split(" (")[0]          # "X (X)" from a rerun: the vote agreed with the name
            named[r["address"]] = (n, r["votes"])
        elif r["kind"] == "self":
            selfc[r["address"]].update(r["detail"].split("|"))
        elif r["kind"] == "file":
            for f in r["file"].split("|"):
                byfile[f].append(r)
    tagged = {r["address"] for r in rows if r["kind"] == "file"}
    for f in list(os.listdir(ROOT)):
        if f.endswith(".md"):
            os.remove(os.path.join(ROOT, f))

    out = ["# Code map — functions by source file", "",
           "Generated by `tools/ghidra/NameFromAsserts.java` from the exe's own assert strings",
           "(`__FILE__`, `__LINE__` and the stringified expression), rendered by",
           "`tools/codemap.py`. Addresses are VAs in `Hellgate_sp_x86.exe` (image base",
           "0x400000, no relocations). The same names are applied in the Ghidra project",
           "`~/ghidra_proj/HG.gpr` (program `hg_sp.exe`).", "",
           "- **name** is set when the function was the target of an assert expression",
           "  `name( ... )` in a caller (votes agreeing / total). Functions still named",
           "  `FUN_xxxxxxxx` were only *tagged* with a file: the asserts inside them name",
           "  their callees, not themselves. The `self?` column lists `name()` strings the",
           "  function references; often, not always, its own name in a message.",
           "- **line** is the smallest `__LINE__` seen in the function, roughly where it",
           "  starts in the source file. Sorting by it puts the file back in source order.", "",
           "Decompile any of them: `make decomp F=\"name1 name2\"` writes `notes/decomp/<name>.c`.",
           "", "| Source file | tagged functions |", "|---|---|"]
    for f in sorted(byfile, key=str.lower):
        page = f.replace(".\\", "").replace("\\", "_").replace("/", "_") + ".md"
        out.append("| [`%s`](%s) | %d |" % (f, page, len(byfile[f])))
    out += ["", "## Named functions not tagged with a file", "",
            "Callees named by votes whose own body carries no `__FILE__` reference.", "",
            "| VA | name | votes |", "|---|---|---|"]
    for a, (n, v) in sorted(named.items(), key=lambda kv: kv[1][0].lower()):
        if a not in tagged:
            out.append("| 0x%s | `%s` | %s |" % (a, n, v))
    out += ["", "## Conflicts (not renamed)", "", "| VA | votes | candidates |", "|---|---|---|"]
    for r in rows:
        if r["kind"] == "conflict":
            out.append("| 0x%s | %s | %s |" % (r["address"], r["votes"], r["detail"].replace("|", "/")))
    open(os.path.join(ROOT, "README.md"), "w").write("\n".join(out) + "\n")

    for f, frows in byfile.items():
        page = f.replace(".\\", "").replace("\\", "_").replace("/", "_") + ".md"
        lines = ["# `%s`" % f, "", "| VA | name | line | self? |", "|---|---|---|---|"]

        def key(r):
            return int(r["line"]) if r["line"].isdigit() else 10 ** 9
        for r in sorted(frows, key=key):
            a = r["address"]
            n = named.get(a, (r["name"], ""))[0]
            lines.append("| 0x%s | `%s` | %s | %s |" % (a, n, r["line"], " ".join(sorted(selfc.get(a, ())))))
        open(os.path.join(ROOT, page), "w").write("\n".join(lines) + "\n")
    print("%d file pages, %d named functions, %d facts" % (len(byfile), len(named), len(rows)))


if __name__ == "__main__":
    main()
